### ISSUE TITLE
theme.mp4 causes movies to appear twice

### ISSUE THREAD

**Issue by orangesky7** [latts9923/script.tvtunes#3]
Hi Rob, 

My video theme files (stored in each movie folder), are causing a duplication when browsing the library. I am using Kodi OpenElec 6.12 and skin Aeon Nox 5.73.

I have updated the advancedsettings.xml file:

<advancedsettings>
    <videolibrary>
        <cleanonupdate>true</cleanonupdate>
        <hideallitems>true</hideallitems>
	<dateadded>0</dateadded>
	<splash>false</splash>
        
        <excludefromscan action="append">
            <regexp>/Themes/</regexp>
            <regexp>[\\/]Themes[\\/]</regexp>
            <regexp>theme([0-9]*)\.(mp4|mkv|avi|mov|m2ts|MP4|MKV|AVI|MOV|M2TS)$</regexp>
        </excludefromscan>
        <excludetvshowsfromscan action="append">
            <regexp>/Themes/</regexp>
            <regexp>[\\/]Themes[\\/]</regexp>
            <regexp>theme([0-9]*)\.(mp4|mkv|avi|mov|m2ts|MP4|MKV|AVI|MOV|M2TS)$</regexp>
        </excludetvshowsfromscan>
        
    </videolibrary>
</advancedsettings>

I removed themes. Cleaned library. Rebooted and they were scanned back in again. Any suggestions please?

Thanks

**Comment by robwebset** [comment]
Sorry, missed this one, I didn't get notified by email on this one for some reason.

Looking at the advancedsettings.xml snippet (Not sure it's pasted correctly) - it looks like you have TvTunes set to store the Themes in a directory called /Themes/Themes/theme.mp4 etc

So I think the regex is incorrect (two Themes directories)? Have you tried using the button in TvTunes settings to correctly add the entry to ignore the theme video files?

Thanks
Rob

**Comment by orangesky7** [comment]
Hi Rob, 

Not sure what happened with the copy paste into GitHub, but I took it straight from the wiki on here and I did also try it via the button, but it still does it... but I worked around it by creating a "themes" sub-folder in each movie folder and using the TVTunes setting to use a "themes" subfolder and i made sure all the kodi source file/folder settings had 'scan recursively' turned off... that will do for now... but i have a couple more questions for you please!!!

Firstly, I hope you can sort things out with the kodi team (your add-on is sooooo good - shame for it to not be in the main forum). 

1) I've been using trailers for video themes - how can i make it so that theme videos start 10 seconds into the trailer (to avoid all the pointless stuff at the start of most trailers)
2) how can i stop the status bar, for video themes, showing the theme's file path - happy for it to just say Theme
3) how can i lower the theme volume (there's an option to turn it up)?
4) is there a different forum that you are using instead of kodi (like tvaddons)?

Thanks,

Pete
P.S. how do I send you a beer! ;-)

**Comment by orangesky7** [comment]
Hi Rob,


I posted on github, but here's what i wrote:


Not sure what happened with the copy paste into GitHub, but I took it straight from the wiki on here and I did also try it via the button, but it still does it... but I worked around it by creating a "themes" sub-folder in each movie folder and using the TVTunes setting to use a "themes" subfolder and i made sure all the kodi source file/folder settings had 'scan recursively' turned off... that will do for now... but i have a couple more questions for you please!!!

Firstly, I hope you can sort things out with the kodi team (your add-on is sooooo good - shame for it to not be in the main forum).

  1.  I've been using trailers for video themes - how can i make it so that theme videos start 10 seconds into the trailer (to avoid all the pointless stuff at the start of most trailers)
  2.  how can i stop the status bar, for video themes, showing the theme's file path - happy for it to just say Theme
  3.  how can i lower the theme volume (there's an option to turn it up)?
  4.  is there a different forum that you are using instead of kodi (like tvaddons)?

Thanks,

Pete
P.S. how do I send you a beer! ;-)



________________________________

**Comment by robwebset** [comment]
Hi Pete,

Strange the advancedsettings.xml button in TvTunes settings is not working for you - it should pick up the "current settings" in TvTunes to generate the correct exclude section (It may need a restart to be enforced).

For your questions:

1) Afraid there is no "set start time" mainly because it is possible that it is a very short theme (say 9 seconds) - however there is an option "Random start time" in TvTunes settings that will start the theme at a random start time.

https://github.com/robwebset/script.tvtunes/wiki#Playback

(I guess in theory it could be an option under that - so a "preferred start time" - that will then fall back to random if it is not possible to determine the file length - or it is too short)

2) I think this may be skin specific - I guess you are using something other than Confluence - in theory the skin author could prevent the bar appearing by detecting the PlayingBackgroundMedia property and then not displaying the bar?

https://github.com/robwebset/script.tvtunes/wiki#TvTunes_Active_Detection

3) There is an option in the TvTunes settings "Theme Volume" which can be used to set the volume when a theme is played (it is the new volume for the theme to play at - not a percentage of the existing volume) - this obviously will not work if you have audio-passthrough enabled on your Kodi installation.

https://github.com/robwebset/script.tvtunes/wiki#Playback

4) No, unfortunately I don't maintain my own forum (nor am I on anyone elses at the moment) - at one point I was thinking about the "Other Repo" that was discussed - I think that is now up and running http://www.urepo.org/ - but not sure anymore - if someone there (@NedScott @zag2me or someone) contacts me about it, then I may look into it. (But at a glance seemed to be enforcing all the Official Repo rules - so most probably isn't an option)

5) Beer always welcome :) button at the bottom of this page: https://github.com/robwebset/script.tvtunes

Thanks
Rob
P.S. Got 2 copies this time :)

**Comment by robwebset** [comment]
For item 1 I have now added an option to the TvTunes settings to allow the "Random" start location to be set to a given time.

https://github.com/robwebset/script.tvtunes/wiki#Playback

I hope that gives you the behaviour you are looking for.

In Repo as: TvTunes v100.5.0

**Comment by orangesky7** [comment]
Hey rob, thanks for that, but both random and the new delay feature are only working for audio themes... could it be because i put all the video themes into a subfolder "themes" within EACH movie folder??? Thanks



On Thu, Dec 1, 2016 at 5:14 PM +0000, "Rob" <notifications@github.com<mailto:notifications@github.com>> wrote:


For item 1 I have now added an option to the TvTunes settings to allow the "Random" start location to be set to a given time.

https://github.com/robwebset/script.tvtunes/wiki#Playback

I hope that gives you the behaviour you are looking for.

In Repo as: TvTunes v100.5.0

-

**Comment by robwebset** [comment]
OK, looks like the getDuration of the Playlist was returning 0 for videos - done some changes to calculate it.

Was thinking about your initial issue of getting themes scrapped into the library - I think this is most likely a bug with the scrapper which is ignoring the advancedsettings.xml file excludes section.

In Repo as: TvTunes v100.5.1

**Comment by orangesky7** [comment]
Hi Rob, that makes a big difference, thanks. Can I please ask if you can split the random/start point option into two: one for audio themes and one for video themes (so i can set them differently) - then it's perfect! Also, what are the chances of being able to have a video option to play the local trailer video instead of the theme video (otherwise I'm doubling up on files)? Thanks! Beer on it's way!

________________________________

**Comment by robwebset** [comment]
Thank you for the donation!!!

As it's you :) I have split it into 2 different options for video and audio.

The best way of linking the theme to a different file is by using a "tvtunes.nfo" file.

https://github.com/robwebset/script.tvtunes/wiki#NFO_File_Support

In Repo as: TvTunes v100.5.2

**Comment by robwebset** [comment]
I am going to close this one now, I hope that everything is OK - but please feel free to re-open this if you still have an issue.

Note: In the process of moving to the urepo.org repository :)

Thanks
Rob
